version: "3.3"

services:

  backend:
    image: "backend-local"
    build: .
    container_name: backend
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    env_file:
      - .env

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}