version: "3.3"

services:

  backend:
    image: "backend-local"
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    env_file:
      - .env

  celery:
    image: "backend-local"
    command: celery -A settings worker -l info --pidfile=/tmp/celerybeat.pid
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env

  celerybeat:
    image: "backend-local"
    command: celery -A settings beat -l info --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.9.5-management
    container_name: rabbitmq
    env_file:
      - .env

  flower:
    image: mher/flower
    command: celery --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_DEFAULT_HOST}:${RABBITMQ_DEFAULT_PORT}// flower
    #    celery --broker=amqp://brokeruser:brokerpassword@rabbitmq:5672// flower
    container_name: flower
    depends_on:
      - rabbitmq
      - celery
    ports:
      - 5555:5555
    env_file:
      - .env

  #  flower:
  #      image: mher/flower:0.9.5
  #      container_name: flower
  #      environment:
  #        - CELERY_BROKER_URL=amqp://brokeruser:brokerpassword@rabbitmq:5672//
  #        - FLOWER_PORT=5555
  #      ports:
  #        - 5555:5555

  nginx:
    image: nginx:1.19
    container_name: "nginx"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:8080"
      # - "80:80"
      - "443:443"
    depends_on:
      - flower

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
    depends_on:
      - postgres
    links:
      - postgres
