# Generated by Django 3.2.3 on 2021-08-07 17:53

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.bank_directory_path),
        ),
        migrations.AlterField(
            model_name='banks',
            name='code_name',
            field=models.CharField(max_length=64),
        ),
    ]
