# Generated by Django 3.2.3 on 2021-08-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateArchive',
        ),
    ]
