# Generated by Django 3.2.3 on 2021-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=255)),
                ('email_from', models.CharField(max_length=60)),
                ('number_phone', models.CharField(max_length=30)),
            ],
        ),
    ]
