# Generated by Django 3.2.3 on 2021-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
