# Generated by Django 3.2.3 on 2021-07-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='code_name',
            field=models.CharField(default='privat', max_length=64, unique=True),
        ),
    ]
