# Generated by Django 3.2.3 on 2021-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_contactus_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
